northsharp/north_app/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='main'),
    path('/about', views.about, name='about'),

    path('/allstudent', views.stud, name='allstud'),
    path('/allempl', views.empl, name='allempl'),
    path('/subj', views.subj, name='subj'),

    path('/grade', views.grade, name='grade'),
    path('/form', views.form, name='form'),
    path('/addstud', views.addstud, name='addstud'),	
    path('/addsubj', views.addsubj, name='addsubj'),

    path('<int:pk>/editsubj', views.editsubj, name='editsubj'),
    path('<int:pk>/deletesubj', views.deletesubj, name='deletesubj'),

    path('<int:pk>/editstud', views.editstud, name='editstud'),
    path('<int:pk>/deletestud', views.deletestud, name='deletestud'),

    path('<int:pk>/editEmpl', views.editEmpl, name='editEmpl'),
    path('<int:pk>/deleteEmpl', views.deleteEmpl, name='deleteEmpl'),

    path('/form', views.form, name='form'),
    path('/addgrade', views.addGrade, name='addgrade'),
    path('/logout', views.user_logout, name='logout'),
    path('/addempl', views.addEmpl, name='addempl')

]

northsharp/northsharp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('north_app.urls')),
]

northsharp/north_app/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.forms import DateInput
from django.contrib.auth.models import BaseUserManager, AbstractUser

class Student(models.Model):
    Class = (
        (1, 'Первый'),
        (2, 'Второй'),
        (3, 'Третий'),
        (4, 'Четвертый'),
        (5, 'Пятый'),
        (6, 'Шестой'),
        (7, 'Седьмой'),
        (8, 'Восьмой'),
        (9, 'Девятый'),
        (10, 'Десятый'),
        (11, 'Одиннадцатый')
    )

    STUDENT = 'student'
    TEACHER = 'teacher'
    DIRECTOR = 'director'
    ROLE_CHOICES = [
        (STUDENT, 'Ученик'),
        (TEACHER, 'Учитель'),
        (DIRECTOR, 'Директор'),
    ]

    name = models.CharField(max_length=100, validators=[
        RegexValidator(regex='^[А-Я][а-я]* [А-Я][а-я]* [А-Я][а-я]*$')])
    class_name = models.IntegerField(choices=Class, validators=[MinValueValidator(1), MaxValueValidator(11)])
    username = models.CharField(max_length=15, null=False,unique=True)
    password = models.CharField(max_length=128, null=False)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)

    def __init__(self, *args, **kwargs):
        super(Student, self).__init__(*args, **kwargs)
        self.role = self.STUDENT
    def __str__(self):
        return self.name
class Subject(models.Model):
    name = models.CharField(max_length=100, unique=True, validators=[
        RegexValidator(regex='^[А-Я][а-я\s\-]*$', message='Имя предмета должно начинаться с заглавной буквы')])

    def __str__(self):
        return self.name


class Employee(models.Model):
    # Остальные поля модели Employee
    teacher = 0
    vice_director = 1
    director = 2
    male = 0
    female = 1
    Position = (
        (teacher, 'Учитель'),
        (vice_director, 'Зам. Директор'),
        (director, 'Директор'),
    )
    Sex = (
        (male, 'Муж'),
        (female, 'Жен'),
    )
    STUDENT = 'student'
    TEACHER = 'teacher'
    DIRECTOR = 'director'
    ROLE_CHOICES = [
        (STUDENT, 'Ученик'),
        (TEACHER, 'Учитель'),
        (DIRECTOR, 'Директор'),
    ]

    name = models.CharField(max_length=100, validators=[
        RegexValidator(regex='^[А-Я][а-я]* [А-Я][а-я]* [А-Я][а-я]*$')])
    position = models.IntegerField(default=0, choices=Position)
    sex = models.IntegerField(default=0, choices=Sex)
    experience = models.PositiveIntegerField()
    birth_day = models.DateField()
    Class_teacher = models.CharField(max_length=100, validators=[
        RegexValidator(r'^\d{3}(?:[А-Я])?$',
                       message='Только трехзначное число или трехзначное число с заглавной буквой в конце')])
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default=TEACHER)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=128, null=False)

    def __str__(self):
        return self.name

class Grade(models.Model):
    Mark = (
        (2, 'Неудовлетворительно'),
        (3, 'Удовлетворительно'),
        (4, 'Хорошо'),
        (5, 'Отлично'),
    )
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    grade = models.PositiveIntegerField(choices=Mark)

    def __str__(self):
        return f'{self.student.class_name} - {self.subject} - {self.grade}'

class Table(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE)

northsharp/north_app/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import Student,Subject,Grade,Table,Employee
from .formstud import studAdd, subjAdd, gradeAdd, emplAdd,subjEdit, subjDelete
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.
from django import forms

class UserLoginForm(forms.Form):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'id': 'username', 'name': 'username', 'class': 'field'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'id': 'password', 'name': 'password', 'class': 'field'}))
    remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'check'}), label='Запомнить меня')

def set_session_data(req, model):
    req.session['username'] = req.POST['username']
    ar = model.objects.get(username__icontains=req.POST['username'])
    req.session['user_role'] = ar.role


# Извлечение данных из сеанса
def get_session_data(req):
    username = req.session.get('username')
    user_role = req.session.get('user_role')
    return [username, user_role]

def auth_stud(req, model):
    if req.POST.get('username'):
        try:
            ar = model.objects.get(username__icontains=req.POST['username'])
            return ar.password == req.POST['password']
        except model.DoesNotExist:
            return False
    return False

def search(request, models):
    if request.POST.get('name'):
        return models.objects.filter(name__icontains = request.POST['name'])
    else:
        return models.objects.all()

def index(request):
    return render(request, "main/index.html",{'user_role' : get_session_data(request)[1]})

def about(request):
    return render(request, "main/about-us.html",{'user_role' : get_session_data(request)[1]})

def user_logout(request):
    logout(request)
    return redirect('form')
@login_required
def stud(request):
    Students = search(request, Student)
    return render(request, "main/allstudent.html",{'student': Students,'user_role' : get_session_data(request)[1]})
@login_required
def empl(request):
    empl = search(request, Employee)
    return render(request, "main/allempl.html",{'empl': empl,'user_role' : get_session_data(request)[1]})
@login_required
def subj(request):
    subj = Subject.objects.all()
    return render(request, "main/subj.html",{'subj': subj,'user_role' : get_session_data(request)[1]})
@login_required
def grade(request):
    if request.session['user_role'] == "student":
        grade = Grade.objects.filter(student__username=request.session['username'])
    else:
        grade = Grade.objects.all()
    return render(request, "main/grade.html",{'grade': grade, 'user_role' : get_session_data(request)[1]})



def form(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            request.session['username'] = request.POST['username']
            request.session['user_role'] = request.POST['role']
            print(request.POST['role'])
            user = authenticate(request, username=username, password=password)
            if username is not None:
                login(request, user)
                # Redirect to a success page.
                return redirect('about')
            else:
                # Return an 'invalid login' error message.
                return render(request, 'main/form.html', {'form': form, 'error': 'Invalid login credentials.'})
    else:
        form = UserLoginForm()
    return render(request, 'main/form.html', {'form': form})

def addstud(request):
    if(type==1):
        return redirect('grade')
    else:
        if request.method == "POST":
            form = studAdd(request.POST)
            if form.is_valid():
                user_stud = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
                user_stud.save()
                form.save()
                return redirect('allstud')
        form = studAdd
        context = {
            'form': form
        }
        return render(request, 'main/add-stud.html', context)

# /Редактирование и удаление
@login_required
def editstud(request, pk):
    if request.method == "POST":
        form = Student.objects.get(pk = pk)
        form.name = request.POST['name']
        form.class_name = request.POST['class_name']
        form.save()
        return redirect('allstud')
    form = studAdd
    context = {
        'form': form
    }
    return render(request, 'main/editstud.html', context)
@login_required
def deletestud(request, pk):
    if request.method == "POST":
        Student.objects.filter(pk = pk).delete()
        return redirect('allstud')
    form = studAdd
    context = {
        'form': form
    }
    return render(request, 'main/deletestud.html', context)
# /


def addsubj(request):
    if request.method == "POST":
        form = subjAdd(request.POST)
        if form.is_valid():
            user_stud = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
            user_stud.save()
            form.save()
            return redirect('main')
    form = subjAdd
    context = {
        'form': form
    }
    return render(request, 'main/addsubj.html', context)

# /Редактирование и удаление
def editsubj(request, pk):
    if request.method == "POST":
        form = Subject.objects.get(pk = pk)
        form.name = request.POST['name']
        form.save()
        return redirect('subj')
    form = subjEdit
    context = {
        'form': form
    }
    return render(request, 'main/editsubj.html', context)

def deletesubj(request, pk):
    if request.method == "POST":
        Subject.objects.filter(pk = pk).delete()
        return redirect('subj')
    form = subjDelete
    context = {
        'form': form
    }
    return render(request, 'main/deletesubj.html', context)
# /


def addGrade(request):
    form = gradeAdd()
    if request.method == 'POST':
        form = gradeAdd(request.POST)
        if form.is_valid():
            form.save()
            return redirect('grade')
    return render(request, 'main/addgrade.html', {'form': form})

def addEmpl(request):
    form = emplAdd()
    if request.method == "POST":
        form = studAdd(request.POST)
        if form.is_valid():
            user_stud = User.objects.create_user(username=request.POST['login'], password=request.POST['password'])
            user_stud.save()
            form.save()
            return redirect('allempl')
    return render(request, 'main/addempl.html', {'form': form})
# /Редактирование и удаление

def editEmpl(request, pk):
    if request.method == "POST":
        form = Employee.objects.get(pk=pk)
        form.name = request.POST['name']
        form.position = request.POST['position']
        form.sex = request.POST['sex']
        form.experience = request.POST['experience']
        form.birth_day = request.POST['birth_day']
        form.Class_teacher = request.POST['Class_teacher']

        form.save()
        return redirect('allempl')
    form = emplAdd
    context = {
        'form': form
    }
    return render(request, 'main/editEmpl.html', context)

def deleteEmpl(request, pk):
    if request.method == "POST":
        Employee.objects.filter(pk = pk).delete()
        return redirect('allempl')
    form = emplAdd
    context = {
        'form': form
    }
    return render(request, 'main/deleteEmpl.html', context)
# /

northsharp/north_app/templates/main/add-stud.html
{% extends 'main/base.html' %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
      {{ form.as_p }}<br>
      <button type="submit">Добавить</button>
    </form>
{% endblock %}

northsharp/north_app/templates/main/addempl.html
{% extends 'main/base.html' %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
      <label>Добавить сотрудника:</label>
      {{ form.as_p }}<br>
      <button type="submit">Добавить</button>
    </form>
{% endblock %}

northsharp/north_app/templates/main/addgrade.html
{% extends 'main/base.html' %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
      <label>Добавить оценку:</label>
      {{ form.as_p }}<br>
      <button type="submit">Добавить</button>
    </form>
{% endblock %}

northsharp/north_app/templates/main/allempl.html
{% extends 'main/base.html' %}
{% load user_extras %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <input name="name" type="text" placeholder="Введите имя:">
    <button type="submit">Поиск</button>
</form>
<table class="tsk">
    <tr>
        <th>Имя</th>
        <th>Должность</th>
        <th>Пол</th>
        <th>Дата рождения</th>
        <th>Стаж работы</th>
        <th>Кабинет</th>
        <th></th>
    </tr>
{% for empl in empl %}
    <tr>
        <td>{{ empl.name }}</td>
        <td>{{ empl.get_position_display }}</td>
        <td>{{ empl.get_sex_display }}</td>
        <td>{{ empl.birth_day }}</td>
        <td>{{ empl.experience }} {{ empl.experience|ru_plural:"год,года,лет" }}</td>
        <td>{{ empl.Class_teacher }}</td>
        <td>{% if user_role != 'student' %}
            <a class="btn btn-primary" href="{% url 'editEmpl' empl.id %}">Изменить</a>
    <a class="btn btn-primary" href="{% url 'deleteEmpl' empl.id %}">Удалить</a>
        {% endif %}</td>
    </tr>
    {% endfor %}
</table>
{% if user_role != 'student' %}
<a class="btn btn-primary" href="{% url 'addempl'%}">Добавить</a>
{% endif %}
{% endblock %}

northsharp/north_app/templates/main/allstudent.html
{% extends 'main/base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <input name="name" type="text" placeholder="Введите имя:">
    <button type="submit">Поиск</button>
</form>
{% for student in student %}

    <div class="tsk">
        <h3>{{ student.name}}</h3>
        <p>Класс: {{student.get_class_name_display}}</p>
        <a class="btn btn-primary" href="{% url 'editstud' student.id %}">Изменить</a>
        <a class="btn btn-primary" href="{% url 'deletestud' student.id %}">Удалить</a>
    </div>

    {% endfor %}
{% if user_role != 'student' %}
<a class="btn btn-primary" href="{% url 'addstud'%}">Добавить</a>
{% endif %}
{% endblock %}

northsharp/north_app/templates/main/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <link rel="stylesheet" href="{% static "css/style.css " %}" />
</head>
<body>
<div class="mar" style="background: white">
    <nav class="navbar navbar-expand-xl navbar-light pt-1 pl-1 pr-1 pb-0 mx-auto d1">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="main-nav" style="margin: 0 4vh 0 9vh">
            <ul class="nav navbar-nav">
                <li class="nav-item mr-4">
                    <a class="nav-link p-0" href="{% url 'main'%}">Главная</a>
                </li>
                <li class="nav-item mr-4">
                    <a class="nav-link p-0" href="{% url 'about'%}">О нас</a>
                </li>

                {% if user.is_authenticated %}
                {% if user_role != 'student' %}
                <li class="nav-item mr-4">
                    <a class="nav-link p-0" href="{% url 'allstud'%}">Ученики</a>
                </li>
                {% endif %}
                <li class="nav-item mr-4">
                    <a class="nav-link p-0" href="{% url 'allempl'%}">Все сотрудники</a>
                </li>
                <li class="nav-item mr-4">
                    <a class="nav-link p-0" href="{% url 'grade'%}">Оценка</a>
                </li>
                {% if user_role != 'student' %}
                <li class="nav-item mr-4">
                    <a class="nav-link p-0" href="{% url 'subj'%}">Предметы</a>
                </li>
                {% endif %}

                <li class="nav-item mr-4">
                    <a class="nav-link p-0" href="{% url 'logout' %}">Выход</a>
                    </li>
                {% else %}
                <li class="nav-item mr-90">
                    <a class="nav-link p-0" href="{% url 'form' %}">Вход</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div style="height: 100vh">
        {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>

northsharp/north_app/templates/main/deleteEmpl.html
{% extends 'main/base.html' %}
{% block content %}
    <form method="POST" class="ml-4 mt-4">
    {% csrf_token %}
        <label>Хотите удалить {{empl.name}}?</label>
        <button type="submit">Удалить</button>
        <a href="{% url 'allempl' %}" class="btn btn-primary">Отмена</a>
    </form>
{% endblock %}

northsharp/north_app/templates/main/deletestud.html
{% extends 'main/base.html' %}
{% block content %}
    <form method="POST" class="ml-4 mt-4">
    {% csrf_token %}
        <label>Хотите удалить {{stud.name}}?</label>
        <button type="submit">Удалить</button>
        <a href="{% url 'allstud' %}" class="btn btn-primary">Отмена</a>
    </form>
{% endblock %}

northsharp/north_app/templates/main/deletesubj.html
{% extends 'main/base.html' %}
{% block content %}
    <form method="POST" class="ml-4 mt-4">
    {% csrf_token %}
        <label>Хотите удалить {{subj.name}}?</label>
        <button type="submit">Удалить</button>
        <a href="{% url 'subj' %}" class="btn btn-primary">Отмена</a>
    </form>
{% endblock %}

northsharp/north_app/templates/main/editstud.html
{% extends 'main/base.html' %}
{% block content %}
    <form method="POST">
    {% csrf_token %}
        <h1>Редактирования ученика</h1>
        <label>Введите ФИО:</label>
        {{ form.name }}<br>
        <label>Введите класс:</label>
        {{ form.class_name }}<br>
        <button type="submit">Редактировать</button>
    </form>
{% endblock %}

northsharp/north_app/templates/main/editsubj.html
{% extends 'main/base.html' %}
{% block content %}
    <form method="POST">
    {% csrf_token %}
        <label>Редактировать название предмета:</label>
        {{ form.name }}<br>
        <button type="submit">Редактировать</button>
    </form>
{% endblock %}

northsharp/north_app/templates/main/grade.html
{% extends 'main/base.html' %}
{% block content %}
<table class="tsk">
        <tr>
        <th>Имя</th>
        <th>Предмет</th>
        <th>Класс</th>
        <th>Оценка</th>
    </tr>
{% for grade in grade %}
<tr>
        <td>{{ grade.student }}</td>
        <td>{{ grade.subject }}</td>
        <td>{{ grade.student.class_name }}</td>
        <td>{{ grade.grade }}</td>
    </tr>
    {% endfor %}
</table>

{% if user_role != 'student' %}
    <a class="btn btn-primary" href="{% url 'addgrade'%}">Добавить</a>
{% endif %}
{% endblock %}

northsharp/north_app/templates/main/new_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <link rel="stylesheet" href="{% static "css/main.css " %}" />
</head>
<body>
    <div class="content">
        <div class="form-md">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

northsharp/north_app/templates/main/report.html
{% extends 'main/base.html' %}
{% block content %}
    <form method="POST" class="ml-4 mt-4">
    {% csrf_token %}


    </form>
{% endblock %}